
export const STICKERS = [
  // Smileys & People
  { id: '😀', name: 'Grinning Face' },
  { id: '😂', name: 'Face with Tears of Joy' },
  { id: '😍', name: 'Smiling Face with Heart-Eyes' },
  { id: '🤔', name: 'Thinking Face' },
  { id: '😎', name: 'Smiling Face with Sunglasses' },
  { id: '🥳', name: 'Partying Face' },
  { id: '🤯', name: 'Exploding Head' },
  { id: '😴', name: 'Sleeping Face' },
  { id: '😭', name: 'Loudly Crying Face' },
  { id: '😇', name: 'Smiling Face with Halo' },
  { id: '😈', name: 'Smiling Face with Horns' },
  { id: '👻', name: 'Ghost' },
  { id: '👽', name: 'Alien' },
  { id: '🤖', name: 'Robot' },
  { id: '👋', name: 'Waving Hand' },
  { id: '👍', name: 'Thumbs Up' },
  { id: '👎', name: 'Thumbs Down' },
  { id: '❤️', name: 'Red Heart' },
  { id: '💔', name: 'Broken Heart' },
  { id: '🔥', name: 'Fire' },
  { id: '⭐', name: 'Star' },
  { id: '✨', name: 'Sparkles' },
  { id: '💯', name: 'Hundred Points' },
  { id: '🧠', name: 'Brain' },
  { id: '👑', name: 'Crown' },
  { id: '🦄', name: 'Unicorn' },
  { id: '🚀', name: 'Rocket' },

  // Animals & Nature
  { id: '🐶', name: 'Dog Face' },
  { id: '🐱', name: 'Cat Face' },
  { id: '🐭', name: 'Mouse Face' },
  { id: '🦊', name: 'Fox' },
  { id: '🐻', name: 'Bear' },
  { id: '🐼', name: 'Panda' },
  { id: '🐨', name: 'Koala' },
  { id: '🦁', name: 'Lion' },
  { id: '🐸', name: 'Frog' },
  { id: '🐵', name: 'Monkey Face' },
  { id: '🐧', name: 'Penguin' },
  { id: '🐔', name: 'Chicken' },
  { id: '🦋', name: 'Butterfly' },
  { id: '🐌', name: 'Snail' },
  { id: '🐞', name: 'Lady Beetle' },
  { id: '🐢', name: 'Turtle' },
  { id: '🐙', name: 'Octopus' },
  { id: '🐬', name: 'Dolphin' },
  { id: '🐳', name: 'Spouting Whale' },
  { id: '🌳', name: 'Deciduous Tree' },
  { id: '🌵', name: 'Cactus' },
  { id: '🌷', name: 'Tulip' },
  { id: '🌸', name: 'Cherry Blossom' },
  { id: '🌹', name: 'Rose' },
  { id: '🌻', name: 'Sunflower' },
  { id: '🍄', name: 'Mushroom' },
  { id: '🌍', name: 'Globe Showing Europe-Africa' },
  { id: '🌕', name: 'Full Moon' },
  { id: '☀️', name: 'Sun' },
  { id: '☁️', name: 'Cloud' },
  { id: '🌈', name: 'Rainbow' },
  { id: '⚡', name: 'High Voltage' },
  { id: '🌊', name: 'Water Wave' },
  
  // Food & Drink
  { id: '🍏', name: 'Green Apple' },
  { id: '🍓', name: 'Strawberry' },
  { id: '🍉', name: 'Watermelon' },
  { id: '🍕', name: 'Pizza' },
  { id: '🍔', name: 'Hamburger' },
  { id: '🍟', name: 'French Fries' },
  { id: '🌮', name: 'Taco' },
  { id: '🍣', name: 'Sushi' },
  { id: '🍩', name: 'Doughnut' },
  { id: '🍪', name: 'Cookie' },
  { id: '🎂', name: 'Birthday Cake' },
  { id: '🍦', name: 'Soft Ice Cream' },
  { id: '🍭', name: 'Lollipop' },
  { id: '🍿', name: 'Popcorn' },
  { id: '☕', name: 'Hot Beverage' },
  { id: '🍺', name: 'Beer Mug' },
  { id: '🍷', name: 'Wine Glass' },

  // Objects
  { id: '⌚', name: 'Watch' },
  { id: '📱', name: 'Mobile Phone' },
  { id: '💻', name: 'Laptop' },
  { id: '📷', name: 'Camera' },
  { id: '💡', name: 'Light Bulb' },
  { id: '📚', name: 'Books' },
  { id: '💰', name: 'Money Bag' },
  { id: '💎', name: 'Gem Stone' },
  { id: '🎸', name: 'Guitar' },
  { id: '⚽', name: 'Soccer Ball' },
  { id: '🏀', name: 'Basketball' },
  { id: '🎲', name: 'Game Die' },
  { id: '🎮', name: 'Video Game' },
  { id: '🔑', name: 'Key' },
  { id: '🔒', name: 'Locked' },
  { id: '🎁', name: 'Wrapped Gift' },
  { id: '🎉', name: 'Party Popper' },
  { id: '🎨', name: 'Artist Palette' },
  { id: '✈️', name: 'Airplane' },
  { id: '🚲', name: 'Bicycle' },
];
